# Generated by Django 4.0.6 on 2022-07-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
