# Generated by Django 4.0.6 on 2022-07-16 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stanzforms', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_filename', models.CharField(max_length=256)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('last_change', models.DateField(blank=True, help_text='Дата-время последнего изменения исходника', null=True)),
                ('approved', models.BooleanField(default=False, help_text='Заказчик утвердил макет')),
                ('approved_date', models.DateField(blank=True, help_text='Дата утверждения', null=True)),
                ('thumb', models.ImageField(blank=True, max_length=200, null=True, upload_to='')),
                ('preview', models.ImageField(blank=True, max_length=200, null=True, upload_to='')),
                ('width', models.PositiveSmallIntegerField(blank=True, help_text='Ширина по тримбоксу, мм', null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, help_text='Высота по тримбоксу, мм', null=True)),
                ('is_cutting', models.BooleanField(blank=True, default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.customer')),
                ('knife', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='stanzforms.knife')),
            ],
        ),
    ]
