# Generated by Django 4.0.6 on 2022-07-16 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_production', models.BooleanField(default=False, help_text='Заказ находится в производстве')),
                ('order', models.IntegerField(help_text='Max order', unique=True, verbose_name='Номер заказа')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование заказа')),
                ('quantity', models.IntegerField(help_text='Общее кол-во заказанных изделий', verbose_name='Тираж')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость, грн.')),
                ('start_date', models.DateField(help_text='Дата оформления заказа', verbose_name='Дата оформления')),
                ('end_date', models.DateField(blank=True, help_text='Предполагаемая дата сдачи заказа', null=True, verbose_name='Сдать до')),
                ('remarks', models.TextField(blank=True, verbose_name='Описание заказа')),
                ('status_ready', models.BooleanField(default=False, help_text='True когда заказ готов к выдаче заказчику.')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.customer', verbose_name='Заказчик')),
                ('status_ready_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrdedNonStandart',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.order')),
            ],
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='OrderMagazine',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.order')),
            ],
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='OrderMontage',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.order')),
            ],
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='OrderPack',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.order')),
            ],
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='PrintSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название листа')),
                ('pressrun', models.IntegerField(blank=True, help_text='Технологический тираж одного листа', null=True, verbose_name='Тираж')),
                ('plates', models.PositiveSmallIntegerField(blank=True, help_text='Кол-во пластин на один лист', null=True, verbose_name='Пластины')),
                ('color_front', models.CharField(blank=True, help_text='Кол-во красок на лице', max_length=10, verbose_name='F')),
                ('color_back', models.CharField(blank=True, help_text='Кол-во красок на обороте, 0 - если без оборота', max_length=10, verbose_name='B')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, help_text='Кол-во одинаковых печатных листов', null=True, verbose_name='Листов')),
                ('turnover', models.CharField(blank=True, choices=[('SingleSide', 'Без оборота'), ('WorkAndTurn', 'Свой оборот'), ('WorkAndThumble', 'Хвост-на-голову'), ('Perfecting', 'Чужой оборот')], max_length=20, null=True, verbose_name='Оборот')),
                ('paper_printing_amount', models.IntegerField(blank=True, help_text='Необходимо выдать листов со склада', verbose_name='Кол-во листов')),
                ('paper_printing_format', models.CharField(blank=True, help_text='Формат бумаги в печать', max_length=20, verbose_name='Формат печати')),
                ('price_sheet', models.FloatField(blank=True, help_text='Стоимость печати', verbose_name='Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('paper', models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.paper', verbose_name='Граммаж и тип бумаги')),
                ('printingpress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.printingpress', verbose_name='Печатная машина')),
            ],
            options={
                'verbose_name': 'Печатный лист',
                'verbose_name_plural': 'Печатные листы',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость, грн.')),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.contractor', verbose_name='Подрядчик')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.technologicaloperation', verbose_name='Операция')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('printsheet', models.ForeignKey(blank=True, help_text='Если оперция не относится к конкретному печатному листу, оставьте это поле пустым', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.printsheet', verbose_name='Печатный лист')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
        migrations.CreateModel(
            name='Detal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название детали')),
                ('width', models.IntegerField(blank=True, help_text='Размер детали, высота, мм', null=True, verbose_name='Высота')),
                ('height', models.IntegerField(blank=True, help_text='Размер детали, ширина, мм', null=True, verbose_name='Ширина')),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Тираж')),
                ('printsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.printsheet')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
            },
        ),
    ]
