# Generated by Django 4.0.6 on 2022-07-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printsheet',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание листа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость, eur.'),
        ),
    ]
