# Generated by Django 4.0.5 on 2022-07-03 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paper'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printsheet',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='printsheet',
            name='outputter',
        ),
        migrations.RemoveField(
            model_name='printsheet',
            name='paper_warehouse_amount',
        ),
        migrations.RemoveField(
            model_name='printsheet',
            name='paper_warehouse_format',
        ),
        migrations.RemoveField(
            model_name='printsheet',
            name='paper_warehouse_unit',
        ),
        migrations.AddField(
            model_name='printsheet',
            name='color_back',
            field=models.CharField(blank=True, max_length=10, verbose_name='Цветность'),
        ),
        migrations.AddField(
            model_name='printsheet',
            name='color_front',
            field=models.CharField(blank=True, max_length=10, verbose_name='Цветность'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='paper',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.paper', verbose_name='Граммаж и тип бумаги'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='paper_printing_amount',
            field=models.CharField(blank=True, help_text='Необходимо выдать листов со склада', max_length=20, verbose_name='Кол-во листов'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='paper_printing_format',
            field=models.CharField(blank=True, help_text='Формат бумаги в печать', max_length=20, verbose_name='Формат печати'),
        ),
    ]
