# Generated by Django 4.0.5 on 2022-07-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_printsheet_colors_remove_printsheet_outputter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_production',
            field=models.BooleanField(default=False, help_text='Заказ находится в производстве'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='color_back',
            field=models.CharField(blank=True, max_length=10, verbose_name='Цвет оборота'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='color_front',
            field=models.CharField(blank=True, max_length=10, verbose_name='Цвет лица'),
        ),
    ]
