# Generated by Django 4.0.5 on 2022-07-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_is_production_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printsheet',
            name='color_back',
            field=models.CharField(blank=True, help_text='Кол-во красок на обороте, 0 - если без оборота', max_length=10, verbose_name='B'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='color_front',
            field=models.CharField(blank=True, help_text='Кол-во красок на лице', max_length=10, verbose_name='F'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Кол-во одинаковых печатных листов', null=True, verbose_name='Листов'),
        ),
    ]
