# Generated by Django 4.0.6 on 2022-07-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_detal_printsheet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printsheet',
            options={'ordering': ['printsheet_sequence'], 'verbose_name': 'Печатный лист', 'verbose_name_plural': 'Печатные листы'},
        ),
        migrations.AddField(
            model_name='printsheet',
            name='printsheet_sequence',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Поле для плагина sortable2 чтобы упорядочивать листы'),
        ),
    ]
